auto_sync = true
sync_frequency = "10m"
search_mode = "fuzzy"
filter_mode = "global"
style = "compact"
inline_height = 20
show_preview = true
max_preview_height = 4
show_help = true
exit_mode = "return-original"
keymap_mode = "emacs"

# History filters
history_filter = [
    "^secret-tool",
    "^adb shell",
    "^ssh",
    "^rsync", 
    "^scp",
    "^sudo",
    "^doas",
    "^su",
    "^cd",
    "^ls",
    "^ll",
    "^la",
    "^pwd",
    "^clear",
    "^exit",
    "^history",
    "^which",
    "^whereis",
    "^whatis",
    "^man",
    "^help",
    "^info",
    "^apropos",
    "^type",
    "^alias",
    "^unalias",
    "^echo",
    "^printf",
    "^cat",
    "^less",
    "^more",
    "^head",
    "^tail",
    "^grep",
    "^egrep",
    "^fgrep",
    "^rg",
    "^ag",
    "^ack",
    "^find",
    "^locate",
    "^updatedb",
    "^date",
    "^cal",
    "^uptime",
    "^w",
    "^who",
    "^whoami",
    "^id",
    "^groups",
    "^finger",
    "^last",
    "^lastlog",
    "^ps",
    "^top",
    "^htop",
    "^btop",
    "^pgrep",
    "^pkill",
    "^killall",
    "^jobs",
    "^bg",
    "^fg",
    "^nohup",
    "^screen",
    "^tmux",
    "^apt",
    "^apt-get",
]

# Workspace and session settings
workspaces = true
common_prefix = ["sudo"]
common_subcommands = [
    "cargo",
    "go", 
    "git",
    "npm",
    "yarn",
    "pnpm",
    "kubectl",
    "docker",
    "podman",
    "systemctl",
    "journalctl",
    "make",
    "cmake",
    "mvn",
    "gradle",
]