input {
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        scroll_factor = 0.25
    }

    sensitivity = 0

    repeat_rate = 25
    repeat_delay = 600

    numlock_by_default = true
}
