windowrule = match:class ^(org.gnome.Calculator)$, float yes

# Picture-in-picture
windowrule {
    match:title = ^(Picture-in-Picture)$
    float = yes
    move = 1492 839
    size = 427 240
    pin = yes
}

# Kitty floating
windowrule = match:class ^(kitty-floating)$, float yes

# Idle inhibit when in fullscreen
windowrule = match:fullscreen true, idle_inhibit fullscreen

